version = 0.1
[default.deploy.parameters]
stack_name = "spring-test-lambda"
resolve_s3 = true
s3_prefix = "spring-test-lambda"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
