AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Spring Cloud Test with AWS Lambda

Globals:
  Function:
    Timeout: 30
    Runtime: java21
    MemorySize: 1024

Resources:
  SpringFunctionTest:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.hei.springcloudtest.handler.LambdaHandler
      Runtime: java21
      Events:
        HelloApi:
          Type: HttpApi
          Properties:
            Path: /hello
            Method: GET
